### ISSUE TITLE
humioctl alerts install – invalid character 'o' in literal null (expecting 'u')

### ISSUE THREAD

**Issue by estahn** [humio/cli#51]
```
humioctl alerts install hipages-general --file="Humio not receiving logs.yaml"
invalid character 'o' in literal null (expecting 'u')
```

```yaml
name: Humio not receiving logs
query:
  queryString: count(as=cnt) | cnt = 0
  start: 5m
  end: now
  isLive: true
description: Humio is not receiving logs. Check the logging operator, fluentd/fluentbit
  pods in namespace logging.
throttleTimeMillis: 900000
silenced: false
notifiers:
- KKiX59EWtAvOAvxjYHhcFHBSh6a2PnLc
```
