### ISSUE TITLE
humioctl profiles set-default - profile not found: strconv.ParseBool: parsing "": invalid syntax

### ISSUE THREAD

**Issue by estahn** [humio/cli#52]
```
humioctl profiles set-default saas
profile not found: strconv.ParseBool: parsing "": invalid syntax
```

```yaml
address: https://humio.k8s.xxx/
ca-certificate-file: ""
insecure: false
profiles:
  saas:
    address: https://cloud.humio.com/
    ca_certificate: ""
    insecure: false
    token: xxx
    username: xxx
  onprem:
    address: https://humio.k8s.xxx/
    ca_certificate: ""
    insecure: false
    token: xxx
    username: xxx
proxy-organization: ""
token: xxx
token-file: ""
```
